services:
  detector:
    build:
      context: .
    env_file: ".env"
    volumes:
      - type: bind
        source: ./clips
        target: /clips
      - type: bind
        source: ./vectors
        target: /app/vectors
        read_only: true
      - type: bind
        source: ./examples
        target: /app/examples
        read_only: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

